stages:
  download:
    cmd: python stages/01_download.py
    deps:
      - stages/01_download.py
    outs:
      - download/01_download
  build: 
    cmd: python stages/02_build.py
    deps:
      - stages/02_build.py
    outs:
      - brick/